spring.application.name=Projekt3

# P?ipojení na MySQL databazi projekt
spring.datasource.url=jdbc:mysql://localhost:3306/projekt
spring.datasource.username=root
spring.datasource.password=

# nastaveni 'validate'zkontroluje, zda tabulka v MySQL sedí s @Entity User
spring.jpa.hibernate.ddl-auto=validate
# Uká?e SQL p?íkazy v konzoli (dobré pro kontrolu)
spring.jpa.show-sql=true
